In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import Perceptron
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
iris =load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
y = iris.target
x= iris.data

In [4]:
# do standard scalar
x = StandardScaler().fit_transform(x)

In [5]:
# split the data
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=101)
xtrain.shape

(120, 4)

In [6]:
# perceptron model building
percptron_model = Perceptron(random_state=101).fit(xtrain,ytrain)

# prediction
pred_xtrain = percptron_model.predict(xtrain)
pred_xtest = percptron_model.predict(xtest)

In [7]:
# check the classification report
print('Classification train:\n',classification_report(ytrain,pred_xtrain))
print('Classification test:\n',classification_report(ytest,pred_xtest))

#confusion matrix 
print('confusion matrix:\n',confusion_matrix(ytrain,pred_xtrain))
print('confusion matrix test:\n',confusion_matrix(ytest,pred_xtest))

# accuracy
print('accuracy_score test:',accuracy_score(ytest,pred_xtest))
print('accuracy_score train:',accuracy_score(ytrain,pred_xtrain))


Classification train:
               precision    recall  f1-score   support

           0       0.91      1.00      0.95        40
           1       0.97      0.79      0.87        38
           2       0.91      0.98      0.94        42

    accuracy                           0.93       120
   macro avg       0.93      0.92      0.92       120
weighted avg       0.93      0.93      0.92       120

Classification test:
               precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.75      0.86        12
           2       0.89      1.00      0.94         8

    accuracy                           0.90        30
   macro avg       0.91      0.92      0.90        30
weighted avg       0.91      0.90      0.90        30

confusion matrix:
 [[40  0  0]
 [ 4 30  4]
 [ 0  1 41]]
confusion matrix test:
 [[10  0  0]
 [ 2  9  1]
 [ 0  0  8]]
accuracy_score test: 0.9
accuracy_score train: 0.925


In [23]:
# k-fold cross val
from sklearn.model_selection import cross_val_score
better_accuracy_test = cross_val_score(percptron_model,xtest,ytest,cv=5)

better_accuracy_train = cross_val_score(percptron_model,xtrain,ytrain,cv=10)

print('better_accuracy_test:',better_accuracy_test)
print('better_accuracy_train:',better_accuracy_train)
better_accuracy_test.mean()

better_accuracy_test: [0.83333333 0.83333333 0.66666667 0.66666667 0.83333333]
better_accuracy_train: [1.         0.83333333 0.91666667 0.83333333 0.75       1.
 0.83333333 0.91666667 1.         0.83333333]


0.7666666666666667